### ISSUE TITLE
Compile on macOS?

### ISSUE THREAD

**Issue by luckman212** [Malandru/subnetting#4]
I'd really love to build a binary for macOS, but I'm hitting a wall
Thought I'd reach out to see if anyone knows how to fix this?

I got this far...

```shell
git clone https://github.com/gabime/spdlog
git clone https://github.com/fmtlib/fmt
git clone https://github.com/Malandru/subnetting && cd subnetting
curl -Lo ./utilities/include/argparse.hpp https://github.com/p-ranav/argparse/releases/download/v2.0/argparse.hpp
cp -R ../spdlog/include/spdlog ./utilities/include
cp -R ../fmt/include/fmt ./utilities/include
mkdir build && cd build
cmake ..
make
```

Which generates this output:
```
$ make
[ 10%] Building CXX object utilities/CMakeFiles/utils.dir/src/arguments.cpp.o
clang: warning: argument unused during compilation: '-static-libgcc' [-Wunused-command-line-argument]
clang: warning: argument unused during compilation: '-static-libstdc++' [-Wunused-command-line-argument]
[ 20%] Building CXX object utilities/CMakeFiles/utils.dir/src/logging.cpp.o
clang: warning: argument unused during compilation: '-static-libgcc' [-Wunused-command-line-argument]
clang: warning: argument unused during compilation: '-static-libstdc++' [-Wunused-command-line-argument]
/Users/luke/Downloads/subnetting/utilities/src/logging.cpp:13:22: error: no member named
      'stdout_color_mt' in namespace 'spdlog'
    logger = spdlog::stdout_color_mt("console");
             ~~~~~~~~^
1 error generated.
make[2]: *** [utilities/CMakeFiles/utils.dir/src/logging.cpp.o] Error 1
make[1]: *** [utilities/CMakeFiles/utils.dir/all] Error 2
make: *** [all] Error 2
```

So I did some googling and came up with something about the `spdlog::stdout_color_mt` syntax for namespaces maybe requiring the `-stdlib=libc++` flag, so I tried that

```
$ make -stdlib=libc++
```
Which generated a wall of text but also ends in an error. It changes something in the makefile though, so now when I run `make` I get this (different) error:

```
$ make
Consolidate compiler generated dependencies of target utils
[ 30%] Built target utils
[ 40%] Building CXX object networking/CMakeFiles/network.dir/src/netparser.cpp.o
clang: warning: argument unused during compilation: '-static-libgcc' [-Wunused-command-line-argument]
clang: warning: argument unused during compilation: '-static-libstdc++' [-Wunused-command-line-argument]
[ 50%] Building CXX object networking/CMakeFiles/network.dir/src/network.cpp.o
clang: warning: argument unused during compilation: '-static-libgcc' [-Wunused-command-line-argument]
clang: warning: argument unused during compilation: '-static-libstdc++' [-Wunused-command-line-argument]
[ 60%] Linking CXX static library libnetwork.a
[ 60%] Built target network
[ 70%] Building CXX object workflow/CMakeFiles/wflow.dir/src/calculator.cpp.o
clang: warning: argument unused during compilation: '-static-libgcc' [-Wunused-command-line-argument]
clang: warning: argument unused during compilation: '-static-libstdc++' [-Wunused-command-line-argument]
[ 80%] Linking CXX static library libwflow.a
[ 80%] Built target wflow
[ 90%] Building CXX object CMakeFiles/subnet.dir/main.cpp.o
clang: warning: argument unused during compilation: '-static-libgcc' [-Wunused-command-line-argument]
clang: warning: argument unused during compilation: '-static-libstdc++' [-Wunused-command-line-argument]
[100%] Linking CXX executable subnet
clang: error: unsupported option '-static-libgcc'
make[2]: *** [subnet] Error 1
make[1]: *** [CMakeFiles/subnet.dir/all] Error 2
make: *** [all] Error 2
```

I'm lost. 🤷‍♂️

**Comment by luckman212** [comment]
https://github.com/gabime/spdlog/issues/1014 looks _maybe_ related, but was closed as fixed in 2017 so...

**Comment by luckman212** [comment]
Also found https://github.com/gabime/spdlog/issues/540 and so tried replacing `stdout_color_mt` with `stdout_logger_mt` but that was also a dead end.

**Comment by Malandru** [comment]
Hi @luckman212, have you tried installing `libspdlog-dev` with your package manager?

I think in macOS is with `brew install spdlog`

Reference: https://formulae.brew.sh/formula/spdlog#default
Let me know if this works.

**Comment by luckman212** [comment]
Thanks @Malandru - yes that's actually what I tried first. Got the same errors, so that's when I switched to cloning the `spdlog` and `fmt` repos directly and trying to build using those. But, I couldn't get it to work.

**Comment by Malandru** [comment]
Can you try adding `-stdlib=libc++` to line number 4 in the `CMakeLists.txt` file?

I mean, replacing the current line with `set (CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -static-libgcc -static-libstdc++ -stdlib=libc++")` then run the next commands inside the `subnetting` folder.

```
rm -rf build/
mkdir build && cd build
cmake ..
make
```

If it does not work, give some time to borrow a mac and do some troubleshooting.

**Comment by luckman212** [comment]
Thank you for trying to help. I changed the `CMakeLists.txt` and added the `-stdlib=libc++` but still got the same error.

```
$ make
Consolidate compiler generated dependencies of target utils
[ 10%] Building CXX object utilities/CMakeFiles/utils.dir/src/logging.cpp.o
clang: warning: argument unused during compilation: '-static-libgcc' [-Wunused-command-line-argument]
clang: warning: argument unused during compilation: '-static-libstdc++' [-Wunused-command-line-argument]
/Users/luke/Downloads/subnetting/utilities/src/logging.cpp:13:22: error: no member named 'stdout_color_mt' in namespace
      'spdlog'
    logger = spdlog::stdout_color_mt("console");
             ~~~~~~~~^
1 error generated.
make[2]: *** [utilities/CMakeFiles/utils.dir/src/logging.cpp.o] Error 1
make[1]: *** [utilities/CMakeFiles/utils.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by Malandru** [comment]
I think the right repository for `libspdlog-dev` that I have installed in Ubuntu is https://github.com/YOU-i-Labs/spdlog

I suggest to follow the same steps that you wrote at the first comment using this repository.

**Comment by Malandru** [comment]
@luckman212, the correct version installed in my system is in the **master** branch of https://github.com/gabime/spdlog, (the original in README.md) but the default branch is `v1.x`, which is very different.

Please try with:
```
git clone https://github.com/gabime/spdlog.git
cd spdlog/
git checkout master
cd ..
```
I think this will fix the issue when running the same steps that you wrote at the first comment.

> Note: brew uses the `1.8.5` tag, that's the reason it does not work.

**Comment by luckman212** [comment]
Ah ha! Yes that was the key.

Using the `master` branch got me 99% of the way there, but build still failed with `clang: error: unsupported option '-static-libgcc'`

So I replaced
```
set (CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -static-libgcc -static-libstdc++")
```
with
```
set (CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -stdlib=libc++ -static-libstdc++")
```
in the `CMakeLists.txt` as per your earlier guidance, and was able to compile successfully.

Here is a full Bash script that achieves zero to compiled binary on macOS:
```bash
#!/usr/bin/env bash

set -e

cd "$HOME/Downloads" || exit 1
git clone https://github.com/gabime/spdlog.git
cd spdlog || exit 1
git checkout master
cd .. || exit 1
git clone https://github.com/fmtlib/fmt
git clone https://github.com/Malandru/subnetting
cd subnetting || exit 1
curl -Lo ./utilities/include/argparse.hpp https://github.com/p-ranav/argparse/releases/download/v2.0/argparse.hpp
cp -R ../spdlog/include/spdlog ./utilities/include
cp -R ../fmt/include/fmt ./utilities/include
mkdir build
cd build || exit 1
cmake ..
sed -i.bak 's/^set (CMAKE_CXX_FLAGS.*$/set (CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -stdlib=libc++ -static-libstdc++")/' ../CMakeLists.txt
make
```

**Comment by Malandru** [comment]
Thanks for your feedback.

I have just pushed some changes to the **dev-env** branch.

Basically, I added the dependencies to the project in another directory to avoid version issues and the flags to compile it in macOS or in Linux.

So, these commands should be enough to build the project.
```
git clone https://github.com/Malandru/subnetting.git
cd subnetting/
git checkout dev-env
mkdir build && cd build
cmake ..
make
```

I would really appreciate your help validating these changes before merge it to the `main` branch.

**Comment by luckman212** [comment]
@Malandru it's almost perfect, but your build flags for `if (APPLE)` in CMakeLists.txt are not right.

`-static-libc++` should be `-stdlib=libc++`

Once I changed that, it builds fine. I submitted this as PR #5 
Thank you again for fixing this!
